### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [mdbassit/fancySelect#2]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by mdbassit** [comment]
Hello, this project is active, but please file a new issue before submitting any pull requests.

Thanks,
M.

**Comment by ghost** [comment]
Hi mdbassit.

> Hello, this project is active, but please file a new issue before submitting any pull requests.
> Thanks,
> M.

thank you for feedback.
