### ISSUE TITLE
Add init for custom selectors only

### ISSUE THREAD

**Issue by dragomano** [mdbassit/fancySelect#5]
I do not want to enable FancySelect for all select elements on the page. How can I enable it for a specific selector, for example `select[id="custom"]`?

Respectively, all styles should to affect only elements with the specified selector, not all standard select elements. Add this feature please.

**Comment by mdbassit** [comment]
Set the global `FancySelectAutoInitialize` variable to `false` before including the `FancySelect` JavaScript to your page:

```html
<script> const FancySelectAutoInitialize = false; </script>
<script src="fancyselect.min.js"></script>
```

Then call `FancySelect.replace()` with your desired element as argument:

```js
const target = document.getElementById('my-custom-element');
FancySelect.replace(target);
```

**Comment by dragomano** [comment]
Thanks, it works perfectly.
